# Sample workflow for building and deploying a Next.js site to GitHub Pages
name: Deploy website to oracle cloud

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show current directory
        run: pwd
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: ls -a && npm run build && ls -a && cd build && ls -a
      - name: Copy output to Nginx folder
        run: ls && cp -a build /var/www/nextjs

  # Deployment job
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to web
        run: npx next start
